# Generated by Django 4.2.14 on 2024-07-29 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chest",
            field=models.FloatField(
                blank=True, help_text="Göğüs çevresi (cm cinsinden)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Boy (cm cinsinden)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hips",
            field=models.FloatField(
                blank=True, help_text="Kalça çevresi (cm cinsinden)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="waist",
            field=models.FloatField(
                blank=True, help_text="Bel çevresi (cm cinsinden)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Kilo (kg cinsinden)", null=True
            ),
        ),
    ]
